local Services=script.Parent:WaitForChild("Services")
local WorldService=require(Services.WorldService)
local DataService=require(Services.DataService)
local MuseumService=require(Services.MuseumService)
local PremiumMuseumService=require(Services.PremiumMuseumService)
local BuildService=require(Services.BuildService)
local MiningService=require(Services.MiningService)
local VisitorService=require(Services.VisitorService)

WorldService:Start()
DataService:Start()
MuseumService:Start(DataService,WorldService)
PremiumMuseumService:Start(WorldService)
BuildService:Start(DataService,WorldService,MuseumService)
MiningService:Start(DataService,WorldService,MuseumService)
VisitorService:Start(DataService,WorldService,MuseumService)

print("[Museum Empire] Server ready — premium museum presets + travelators")
