local Services=script.Parent:WaitForChild("Services")
local WorldService=require(Services.WorldService)
local DataService=require(Services.DataService)
local MuseumService=require(Services.MuseumService)
local PremiumMuseumService=require(Services.PremiumMuseumService)
local BuildService=require(Services.BuildService)
local MiningService=require(Services.MiningService)
local VisitorService=require(Services.VisitorService)
local FoundationService=require(Services.FoundationService)
local OperationsService=require(Services.OperationsService)
local ExpansionService=require(Services.ExpansionService)
local WorldGameplayService=require(Services.WorldGameplayService)
local AssetImportService=require(Services.AssetImportService)
local MuseumAssetPlacementService=require(Services.MuseumAssetPlacementService)

WorldService:Start()
AssetImportService:Start()
DataService:Start()
MuseumService:Start(DataService,WorldService)
PremiumMuseumService:Start(WorldService)
MuseumAssetPlacementService:Start(AssetImportService,WorldService)
BuildService:Start(DataService,WorldService,MuseumService)
MiningService:Start(DataService,WorldService,MuseumService)
OperationsService:Start(DataService)
VisitorService:Start(DataService,WorldService,MuseumService)
FoundationService:Start(DataService,MuseumService)
ExpansionService:Start(DataService,MuseumService)
WorldGameplayService:Start(DataService,MuseumService,WorldService)

print("[Museum Empire] Server ready — sanitized asset library, placed museum decor + full gameplay foundation")
