local BuildConfig = {
	DataStoreName = "PropertyEmpireV2_Builds_v1",
	DataVersion = 2,
	GridSize = 2,
	LevelHeight = 8,
	MaxLevels = 8,
	MaxPiecesPerLot = 450,
	BoundaryMargin = 1,
	PlacementCooldown = 0.12,
	RemovalCooldown = 0.18,
	SaveDebounceSeconds = 8,
	RemovalRefundRate = 0.5,
	CatalogOrder = {
		"Floor",
		"Wall",
		"Doorway",
		"Window",
		"Stair",
		"WoodFloor",
		"BrickWall",
		"GlassWall",
		"MarbleWall",
	},
	Catalog = {
		Floor = {
			DisplayName = "Piso",
			Size = Vector3.new(8, 1, 8),
			Material = Enum.Material.Concrete,
			Color = Color3.fromRGB(198, 198, 198),
			Category = "Basic",
			Slot = "Floor",
			Price = 0,
		},
		Wall = {
			DisplayName = "Parede",
			Size = Vector3.new(8, 8, 1),
			Material = Enum.Material.SmoothPlastic,
			Color = Color3.fromRGB(229, 226, 218),
			Category = "Basic",
			Slot = "Wall",
			Price = 0,
		},
		Doorway = {
			DisplayName = "Porta",
			Size = Vector3.new(8, 8, 1),
			Material = Enum.Material.SmoothPlastic,
			Color = Color3.fromRGB(220, 216, 205),
			Category = "Basic",
			Slot = "Wall",
			Price = 0,
		},
		Window = {
			DisplayName = "Janela",
			Size = Vector3.new(8, 8, 1),
			Material = Enum.Material.SmoothPlastic,
			Color = Color3.fromRGB(220, 216, 205),
			Category = "Basic",
			Slot = "Wall",
			Price = 0,
		},
		Stair = {
			DisplayName = "Escada",
			Size = Vector3.new(8, 8, 16),
			Material = Enum.Material.Concrete,
			Color = Color3.fromRGB(190, 190, 190),
			Category = "Basic",
			Slot = "Stair",
			Price = 0,
		},
		WoodFloor = {
			DisplayName = "Piso de Madeira",
			Size = Vector3.new(8, 1, 8),
			Material = Enum.Material.WoodPlanks,
			Color = Color3.fromRGB(151, 105, 67),
			Category = "Premium",
			Slot = "Floor",
			Price = 250,
		},
		BrickWall = {
			DisplayName = "Parede de Tijolos",
			Size = Vector3.new(8, 8, 1),
			Material = Enum.Material.Brick,
			Color = Color3.fromRGB(151, 79, 65),
			Category = "Premium",
			Slot = "Wall",
			Price = 350,
		},
		GlassWall = {
			DisplayName = "Parede de Vidro",
			Size = Vector3.new(8, 8, 1),
			Material = Enum.Material.Glass,
			Color = Color3.fromRGB(156, 210, 226),
			Transparency = 0.3,
			Category = "Premium",
			Slot = "Wall",
			Price = 500,
		},
		MarbleWall = {
			DisplayName = "Parede de Mármore",
			Size = Vector3.new(8, 8, 1),
			Material = Enum.Material.Marble,
			Color = Color3.fromRGB(226, 226, 220),
			Category = "Premium",
			Slot = "Wall",
			Price = 750,
		},
	},
}

return table.freeze(BuildConfig)
