local Catalog = {}

Catalog.GridSize = 2
Catalog.FloorHeight = 8
Catalog.MaxPieces = 500
Catalog.RefundRate = 0.5
Catalog.PlotHalfWidth = 56
Catalog.PlotHalfDepth = 44

Catalog.CategoryOrder = {
	"Estrutura",
	"Exterior",
	"Exposição",
	"Interior",
	"Segurança",
}

Catalog.Items = {
	Floor = {
		Id = "Floor",
		Name = "Piso",
		Category = "Estrutura",
		Price = 250,
		Size = Vector3.new(8, 1, 8),
		YOffset = 0.5,
		Material = Enum.Material.Concrete,
		Color = Color3.fromRGB(206, 205, 199),
		Layer = "Surface",
		MinLevel = 1,
		MinPrestige = 0,
	},
	Wall = {
		Id = "Wall",
		Name = "Parede",
		Category = "Estrutura",
		Price = 350,
		Size = Vector3.new(8, 8, 1),
		YOffset = 4,
		Material = Enum.Material.SmoothPlastic,
		Color = Color3.fromRGB(233, 232, 227),
		Layer = "Structure",
		MinLevel = 1,
		MinPrestige = 0,
	},
	HalfWall = {
		Id = "HalfWall",
		Name = "Meia parede",
		Category = "Estrutura",
		Price = 220,
		Size = Vector3.new(8, 4, 1),
		YOffset = 2,
		Material = Enum.Material.SmoothPlastic,
		Color = Color3.fromRGB(226, 225, 220),
		Layer = "Structure",
		MinLevel = 1,
		MinPrestige = 0,
	},
	Pillar = {
		Id = "Pillar",
		Name = "Pilar",
		Category = "Estrutura",
		Price = 180,
		Size = Vector3.new(1, 8, 1),
		YOffset = 4,
		Material = Enum.Material.Concrete,
		Color = Color3.fromRGB(201, 199, 193),
		Layer = "Structure",
		MinLevel = 1,
		MinPrestige = 0,
	},
	Beam = {
		Id = "Beam",
		Name = "Viga",
		Category = "Estrutura",
		Price = 180,
		Size = Vector3.new(8, 1, 1),
		YOffset = 7.5,
		Material = Enum.Material.Concrete,
		Color = Color3.fromRGB(196, 194, 189),
		Layer = "Structure",
		MinLevel = 1,
		MinPrestige = 0,
	},
	Ceiling = {
		Id = "Ceiling",
		Name = "Teto",
		Category = "Estrutura",
		Price = 300,
		Size = Vector3.new(8, 1, 8),
		YOffset = 8,
		Material = Enum.Material.Concrete,
		Color = Color3.fromRGB(221, 220, 215),
		Layer = "Surface",
		MinLevel = 1,
		MinPrestige = 0,
	},
	Doorway = {
		Id = "Doorway",
		Name = "Vão de porta",
		Category = "Estrutura",
		Price = 500,
		Size = Vector3.new(8, 8, 1),
		YOffset = 4,
		Material = Enum.Material.SmoothPlastic,
		Color = Color3.fromRGB(230, 229, 224),
		Layer = "Structure",
		MinLevel = 1,
		MinPrestige = 0,
		Composite = "Doorway",
	},
	Window = {
		Id = "Window",
		Name = "Janela",
		Category = "Estrutura",
		Price = 650,
		Size = Vector3.new(8, 8, 1),
		YOffset = 4,
		Material = Enum.Material.SmoothPlastic,
		Color = Color3.fromRGB(224, 224, 221),
		Layer = "Structure",
		MinLevel = 1,
		MinPrestige = 10,
		Composite = "Window",
	},
	Stair = {
		Id = "Stair",
		Name = "Escada",
		Category = "Estrutura",
		Price = 1200,
		Size = Vector3.new(8, 8, 12),
		YOffset = 4,
		Material = Enum.Material.Concrete,
		Color = Color3.fromRGB(190, 188, 183),
		Layer = "Structure",
		MinLevel = 2,
		MinPrestige = 25,
		Composite = "Stair",
	},
	GlassWall = {
		Id = "GlassWall",
		Name = "Parede de vidro",
		Category = "Estrutura",
		Price = 1500,
		Size = Vector3.new(8, 8, 1),
		YOffset = 4,
		Material = Enum.Material.Glass,
		Color = Color3.fromRGB(159, 213, 229),
		Transparency = 0.35,
		Layer = "Structure",
		MinLevel = 2,
		MinPrestige = 35,
	},

	Grass = {
		Id = "Grass",
		Name = "Grama",
		Category = "Exterior",
		Price = 80,
		Size = Vector3.new(8, 0.5, 8),
		YOffset = 0.25,
		Material = Enum.Material.Grass,
		Color = Color3.fromRGB(87, 128, 77),
		Layer = "Surface",
		MinLevel = 1,
		MinPrestige = 0,
	},
	StonePath = {
		Id = "StonePath",
		Name = "Calçada de pedra",
		Category = "Exterior",
		Price = 120,
		Size = Vector3.new(8, 0.5, 8),
		YOffset = 0.25,
		Material = Enum.Material.Cobblestone,
		Color = Color3.fromRGB(132, 130, 124),
		Layer = "Surface",
		MinLevel = 1,
		MinPrestige = 0,
	},
	Fence = {
		Id = "Fence",
		Name = "Cerca",
		Category = "Exterior",
		Price = 260,
		Size = Vector3.new(8, 3, 0.5),
		YOffset = 1.5,
		Material = Enum.Material.WoodPlanks,
		Color = Color3.fromRGB(111, 78, 52),
		Layer = "Structure",
		MinLevel = 1,
		MinPrestige = 0,
	},
	Hedge = {
		Id = "Hedge",
		Name = "Cerca viva",
		Category = "Exterior",
		Price = 320,
		Size = Vector3.new(8, 3, 2),
		YOffset = 1.5,
		Material = Enum.Material.Grass,
		Color = Color3.fromRGB(66, 112, 62),
		Layer = "Structure",
		MinLevel = 1,
		MinPrestige = 10,
	},

	Pedestal = {
		Id = "Pedestal",
		Name = "Pedestal de exposição",
		Category = "Exposição",
		Price = 600,
		Size = Vector3.new(3, 3, 3),
		YOffset = 1.5,
		Material = Enum.Material.Marble,
		Color = Color3.fromRGB(213, 211, 204),
		Layer = "Fixture",
		MinLevel = 1,
		MinPrestige = 0,
	},
	SmallCase = {
		Id = "SmallCase",
		Name = "Vitrine pequena",
		Category = "Exposição",
		Price = 1200,
		Size = Vector3.new(5, 5, 5),
		YOffset = 2.5,
		Material = Enum.Material.Glass,
		Color = Color3.fromRGB(173, 216, 230),
		Transparency = 0.45,
		Layer = "Fixture",
		MinLevel = 1,
		MinPrestige = 15,
	},
	LargeCase = {
		Id = "LargeCase",
		Name = "Vitrine grande",
		Category = "Exposição",
		Price = 3000,
		Size = Vector3.new(8, 6, 5),
		YOffset = 3,
		Material = Enum.Material.Glass,
		Color = Color3.fromRGB(165, 211, 227),
		Transparency = 0.42,
		Layer = "Fixture",
		MinLevel = 2,
		MinPrestige = 45,
	},
	Spotlight = {
		Id = "Spotlight",
		Name = "Luz de destaque",
		Category = "Exposição",
		Price = 900,
		Size = Vector3.new(2, 1, 2),
		YOffset = 7.4,
		Material = Enum.Material.Metal,
		Color = Color3.fromRGB(50, 52, 58),
		Layer = "Fixture",
		MinLevel = 1,
		MinPrestige = 20,
	},

	Bench = {
		Id = "Bench",
		Name = "Banco",
		Category = "Interior",
		Price = 450,
		Size = Vector3.new(6, 2, 2),
		YOffset = 1,
		Material = Enum.Material.Wood,
		Color = Color3.fromRGB(123, 89, 59),
		Layer = "Fixture",
		MinLevel = 1,
		MinPrestige = 0,
	},
	InfoPanel = {
		Id = "InfoPanel",
		Name = "Painel informativo",
		Category = "Interior",
		Price = 350,
		Size = Vector3.new(4, 3, 0.5),
		YOffset = 1.5,
		Material = Enum.Material.SmoothPlastic,
		Color = Color3.fromRGB(48, 52, 61),
		Layer = "Fixture",
		MinLevel = 1,
		MinPrestige = 0,
	},
	InteriorLamp = {
		Id = "InteriorLamp",
		Name = "Luminária",
		Category = "Interior",
		Price = 500,
		Size = Vector3.new(1, 1, 1),
		YOffset = 7.3,
		Material = Enum.Material.Metal,
		Color = Color3.fromRGB(70, 72, 78),
		Layer = "Fixture",
		MinLevel = 1,
		MinPrestige = 5,
	},

	Camera = {
		Id = "Camera",
		Name = "Câmera de segurança",
		Category = "Segurança",
		Price = 1800,
		Size = Vector3.new(1.5, 1, 1.5),
		YOffset = 6.8,
		Material = Enum.Material.Metal,
		Color = Color3.fromRGB(54, 57, 64),
		Layer = "Fixture",
		MinLevel = 2,
		MinPrestige = 30,
	},
	Alarm = {
		Id = "Alarm",
		Name = "Alarme",
		Category = "Segurança",
		Price = 2500,
		Size = Vector3.new(2, 1, 1),
		YOffset = 6.5,
		Material = Enum.Material.Metal,
		Color = Color3.fromRGB(153, 57, 57),
		Layer = "Fixture",
		MinLevel = 2,
		MinPrestige = 45,
	},
	MotionSensor = {
		Id = "MotionSensor",
		Name = "Sensor de movimento",
		Category = "Segurança",
		Price = 3200,
		Size = Vector3.new(1, 1, 1),
		YOffset = 6.5,
		Material = Enum.Material.Metal,
		Color = Color3.fromRGB(70, 82, 94),
		Layer = "Fixture",
		MinLevel = 3,
		MinPrestige = 80,
	},
	Safe = {
		Id = "Safe",
		Name = "Cofre",
		Category = "Segurança",
		Price = 7500,
		Size = Vector3.new(4, 4, 4),
		YOffset = 2,
		Material = Enum.Material.Metal,
		Color = Color3.fromRGB(60, 63, 68),
		Layer = "Fixture",
		MinLevel = 3,
		MinPrestige = 100,
	},
}

function Catalog.Get(id)
	return Catalog.Items[id]
end

function Catalog.GetOrderedItems()
	local result = {}
	for _, category in ipairs(Catalog.CategoryOrder) do
		local bucket = {}
		for _, item in pairs(Catalog.Items) do
			if item.Category == category then
				table.insert(bucket, item)
			end
		end
		table.sort(bucket, function(a, b)
			if a.MinLevel ~= b.MinLevel then
				return a.MinLevel < b.MinLevel
			end
			if a.MinPrestige ~= b.MinPrestige then
				return a.MinPrestige < b.MinPrestige
			end
			return a.Price < b.Price
		end)
		for _, item in ipairs(bucket) do
			table.insert(result, item)
		end
	end
	return result
end

return table.freeze(Catalog)
