local MiningMuseumConfig = {
	DataStoreName = "PropertyEmpireV2_MiningMuseum_v1",
	DataVersion = 1,
	MiningCooldown = 8,
	MuseumOpenCooldown = 20,
	AppraisalFee = 250,
	MinimumCashTransfer = 100,
	MaximumCashTransfer = 100000,
	MaxSpecimensPerBusiness = 60,
	MaxDisplayedSpecimens = 12,
	MinSpecimenPrice = 100,
	MaxSpecimenPrice = 50000,
	SpecimenPriceStep = 250,
	MuseumBaseRevenue = 200,
	MuseumRevenuePerPrestige = 25,
	MuseumMaxRevenue = 5000,
	RarityOrder = {
		"Common",
		"Uncommon",
		"Rare",
		"Epic",
		"Legendary",
	},
	RarityLabels = {
		Common = "Comum",
		Uncommon = "Incomum",
		Rare = "Raro",
		Epic = "Épico",
		Legendary = "Lendário",
	},
	RarityPrestige = {
		Common = 1,
		Uncommon = 3,
		Rare = 8,
		Epic = 20,
		Legendary = 50,
	},
	Finds = {
		{
			Id = "QuartzCluster",
			DisplayName = "Aglomerado de Quartzo",
			Rarity = "Common",
			Weight = 42,
			BaseValue = 150,
			FakeChance = 0,
		},
		{
			Id = "GoldNugget",
			DisplayName = "Pepita de Ouro",
			Rarity = "Uncommon",
			Weight = 28,
			BaseValue = 650,
			FakeChance = 0.04,
		},
		{
			Id = "EmeraldCrystal",
			DisplayName = "Cristal de Esmeralda",
			Rarity = "Rare",
			Weight = 16,
			BaseValue = 1800,
			FakeChance = 0.12,
		},
		{
			Id = "DiamondRough",
			DisplayName = "Diamante Bruto",
			Rarity = "Epic",
			Weight = 9,
			BaseValue = 6000,
			FakeChance = 0.35,
		},
		{
			Id = "AncientFossil",
			DisplayName = "Fóssil Ancestral",
			Rarity = "Legendary",
			Weight = 5,
			BaseValue = 14000,
			FakeChance = 0.20,
		},
	},
}

return table.freeze(MiningMuseumConfig)
